name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux1_x86_64

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        cat /etc/os-release
